<?php
/**
 * Jason Alvis Twitter
 *
 * @category    Jasonalvis
 * @package     Jasonalvis_Twitter
 * @author      Jason Alvis <hello@jasonalvis.co.uk>
 * @copyright   Copyright (c) 2016 Jason Alvis (http://jasonalvis.co.uk)
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php if($this->getEnabled() && $tweets = $this->getSearchTweets()): ?>
    <div>
        <h2><?php echo __('Search Tweets'); ?></h2>

        <ul>
            <?php foreach($tweets as $tweet): ?>
                <li>
                    <?php if($this->getShowAvatar()): ?>
                        <p><img src="<?php echo $tweet['user_image']; ?>" alt="<?php echo $tweet['user_name']; ?>"></p>
                    <?php endif; ?>

                    <?php if($this->getShowScreenName()): ?>
                        <p><?php echo trim($tweet["user_name"]); ?> - <?php echo $tweet["screen_name"]; ?></p>
                    <?php endif; ?>

                    <p><?php echo trim($tweet["tweet"]); ?></p>

                    <?php if($this->getShowMedia() && $this->getShowMediaImages() && isset($tweet["media_url"]) && isset($tweet["media_image_url"])): ?>
                        <a href="<?php echo $tweet["media_url"]; ?>">
                            <img src="<?php echo $tweet["media_image_url"] . ':' . $this->getMediaImageSize()  ?>" alt="">
                        </a>
                    <?php endif; ?>

                    <p><?php echo trim($tweet["time"]); ?></p>

                    <?php if($this->getShowReply()): ?>
                        <a href="https://twitter.com/intent/tweet?in_reply_to=<?php echo $tweet["id"]; ?>" target="_blank">
                            <?php echo __('Reply'); ?>
                        </a>
                    <?php endif; ?>

                    <?php if($this->getShowRetweet()): ?>
                        <a href="https://twitter.com/intent/retweet?tweet_id=<?php echo $tweet["id"]; ?>" target="_blank">
                            <?php echo __('Retweet'); ?>
                        </a>
                    <?php endif; ?>

                    <?php if($this->getShowFavorite()): ?>
                        <a href="https://twitter.com/intent/like?tweet_id=<?php echo $tweet["id"]; ?>" target="_blank">
                            <?php echo __('Favorite'); ?>
                        </a>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>